In [2]:
import numpy as np

In [5]:
"""
Computung reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1,10,size = 5)
print(values)

compute_reciprocals(values)

[9 5 7 8 7]


array([0.11111111, 0.2       , 0.14285714, 0.125     , 0.14285714])

In [10]:
"""
comparison: Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1,100, size=1000000)

#Looping on a big array
%timeit compute_reciprocals(big_array)

#Vectorized operations
%timeit 1 / big_array 

2.21 s ± 120 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.17 ms ± 521 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size = (5))
arr2 = np.random.randint(10, size = (5))
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1)
arr3 =  arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size = (3,5))
print(arr4)

arr5 = arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [25]:
"""
Ufuncs: Array Arithmetic
"""

x = np.arange(4)
print("x     =  ", x)
print("x +5  =  ", x+5)
print("x -5  =  ", x-5)
print("x * 2 =  ", x*5)
print("x / 2 =  ", x/5)
print("x **2 =  ", x**5)

# print("x +5  =  ", np.add(x,5))
# print("x -5  =  ", x-5)
# print("x * 2 =  ", x*5)
# print("x / 2 =  ", x/5)
# print("x **2 =  ", x**5)

x     =   [0 1 2 3]
x +5  =   [5 6 7 8]
x -5  =   [-5 -4 -3 -2]
x * 2 =   [ 0  5 10 15]
x / 2 =   [0.  0.2 0.4 0.6]
x **2 =   [  0   1  32 243]


In [29]:
"""
Ufuncs: Absolute Value
"""

x= np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j,0])
print(np.abs(x))


[2 1 0 1 2]
[5. 5. 2. 0.]


In [32]:
"""
Ufuncs: Trigonometric Functions
"""

theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [35]:
"""
Ufuncs: Aggregation
"""

x = np.arange(1,5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [37]:
#accumulate()
x = np.arange(1,15)
print(x)

accum = np.add.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]


In [7]:
#summing the Values in an Array

np.random.seed(2)
arr = np.random.rand(1000000)

print(arr)
print('sum = ', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum =  499468.5166853333
82.6 ms ± 4.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentitle =", np.percentitle(arr, 90))
print(np.any(arr>1))
print(np.all(arr>0))


max = 0.9999976661165695
min = 9.475783189216713e-07
mean = 0.49946851668533326
median = 0.49948650836352526


AttributeError: module 'numpy' has no attribute 'percentitle'

In [44]:
np.random.seed(5)

arr = np.random.randint(10, size =(3,4))
print(arr)

print(np.sum(arr, axis=0))#세로 row

print(np.sum(arr, axis=1))#가로 column

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
