In [1]:
import numpy as np

In [7]:
"""
Introduction to Broadcasting
"""

#Broadcasting 2D + 1D arrays

a = np.ones((3,4)) # 3*3 size
print(a)

b=np.arange(4)
print(b)

print(a+b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [10]:
#Broadcast both arrays

a= np.arange(3)
print(a)
a= a[:,np.newaxis]
print(a)
b=np.arange(3)
print(b)

print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
"""
Comparisons, Masks, and Boolean Logic
"""

x = np.array([1,2,3,4,5])
print(x<3)
print(x!=3)

[ True  True False False False]
[ True  True False  True  True]


In [16]:
#bool masking for multi-dimensional arrays

np.random.seed(0)
a= np.random.randint(10,size=(3,4))

print(a<5)

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]


In [24]:
"""
Working with Boolean Arrays
"""

print(a)
print(np.count_nonzero(a<6)) #True 1, False 0 
# print(np.sum(a<6))

print(np.any(a >8))
print(np.all(a > 1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
True
False


In [26]:
#Masking operations

print(a)
print(a < 5)
print(a[a < 5])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


In [29]:
"""
Fancy Indexing
"""

np.random.seed(1)
x = np.random.randint(100, size=10)
print(x)

a = x[2]; b=x[4]; c = x[6] #한줄에 여러 코드를 쓸 때 사용 ;
print(a,b,c)

ind = [2,4,6]
print(x[ind])

[37 12 72  9 75  5 79 64 16  1]
72 75 79
[72 75 79]


In [32]:
#For n-D arrays
x = np.random.randint(10,size = (3,5))
print(x)

row = [0,1,2]
col = [2,1,4]

print(x[row,col])

[[7 3 6 5 1]
 [9 3 4 8 1]
 [4 0 3 9 2]]
[6 3 2]


In [36]:
#For n-D arrays with broadcasting

print(x)
row = np.array([0,1,2]) # list -> ndarray
col = np.array([2,1,4])

x[row[:,np.newaxis], col]


[[7 3 6 5 1]
 [9 3 4 8 1]
 [4 0 3 9 2]]


array([[6, 3, 1],
       [4, 3, 1],
       [3, 0, 2]])

In [45]:
"""
Combined Indexing
"""

x = np.arange(1,13).reshape(3,4)
print(x)
ind = x[2,[2,0,1]] #기본 인덱싱+ 팬시 인덱싱
print(ind)

print(x[1:,[2,0,1]]) #슬라이싱 + 팬시 인덱싱

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[11  9 10]
[[ 7  5  6]
 [11  9 10]]
